name: CI
on:
  push:
    branches:
    - main
    tags:
    - "v*"
  pull_request:

jobs:
  test:
    name: Test ${{ matrix.os-and-arch.os }}-${{ matrix.os-and-arch.arch }} / java ${{ matrix.java }}
    runs-on: ${{ matrix.os-and-arch.os }}
    strategy:
      fail-fast: false
      matrix:
        java: [8, 11, 17, 21, 23]
        os-and-arch: [ 
            {os: "ubuntu-latest", arch: "X64"},
            {os: "windows-latest", arch: "X64"},
            {os: "macos-13", arch: "ARM64"},
            {os: "macos-14", arch: "ARM64"}
        ]
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: coursier/cache-action@v6.4
    # install JDK 23, always needed for multi-release JAR
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: |
          23
          ${{ matrix.java }}
    - name: Compile JDK23 module
      run: |
        export JAVA_HOME=$JAVA_HOME_23_${{matrix.os-and-arch.arch}}
        ./mill jdk23.compile
    - name: Test
      run: ./mill __.test
    - name: Publish locally
      run: ./mill __.publishLocal # This ensures that javadoc generation succeeds in particular

  publish:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: coursier/cache-action@v6.4
    - uses: coursier/setup-action@v1
      with:
        jvm: "23"
    - name: Publish
      run: ./mill mill.scalalib.PublishModule/ --sonatypeUri https://s01.oss.sonatype.org/service/local --sonatypeSnapshotUri https://s01.oss.sonatype.org/content/repositories/snapshots
      env:
        MILL_PGP_SECRET_BASE64: ${{ secrets.PUBLISH_SECRET_KEY }}
        MILL_PGP_PASSPHRASE: ${{ secrets.PUBLISH_SECRET_KEY_PASSWORD }}
        MILL_SONATYPE_USERNAME: ${{ secrets.PUBLISH_USER }}
        MILL_SONATYPE_PASSWORD: ${{ secrets.PUBLISH_PASSWORD }}
